### ISSUE TITLE
Bad Decrypt on account

### ISSUE THREAD

**Issue by arj154** [antoinelamy/fastlane-plugin-lastpass#1]
Hi, 

I seem to have an issue where it says bad decrypt when I run the list command of;
`fastlane run lastpass username:"username" password:"password" list:true`

``/usr/local/lib/ruby/gems/2.4.0/gems/lastpass-1.5.0/lib/lastpass/parser.rb:282:in `final': [!] bad decrypt (OpenSSL::Cipher::CipherError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/lastpass-1.5.0/lib/lastpass/parser.rb:282:in `decode_aes256'``

also i noticed that something related to the parser is deprecated as this happens as soon as i trigger setup
`/usr/local/lib/ruby/gems/2.4.0/gems/lastpass-1.5.0/lib/lastpass/parser.rb:278: warning: constant OpenSSL::Cipher::Cipher is deprecated`

I created a new lastpass account and this seems to work fine so I wonder if its related to whether its a paid account or the account type? 

Let me know if there's anything I can provide.

**Comment by antoinelamy** [comment]
Thanks for the report, this doesn’t look related to this plugin but with the LastPass client it uses. There already been similar reports, not exactly sure what is the root cause here. Do you have two-factor authentication enabled? What is your ruby and dependencies versions?

https://github.com/detunized/lastpass-ruby/issues/9

**Comment by arj154** [comment]
- Two factor is not enabled
and the rubygem version and Ruby version is this;
`RUBYGEMS VERSION: 3.0.2
  - RUBY VERSION: 2.4.2 (2017-09-14 patchlevel 198) [x86_64-darwin16]`
